// ============================================================
// ALU — Arithmetic Logic Unit
// RV32I Operations
// Author  : Jeevan
// Project : RISC-V RV32IM Processor
// Phase   : 1 (Single Cycle) — reused in all phases
//
// WHAT THIS MODULE DOES:
//   The ALU is the "calculator" of the CPU. It takes two 32-bit
//   numbers (A and B) and performs one operation on them based on
//   the alu_ctrl signal. The result and status flags are output.
//
//   Think of it like a calculator that can only do one operation
//   at a time, chosen by a 4-bit control code.
// ============================================================

module alu (
    input  wire [31:0] A,         // Operand A — comes from Register File (rs1) or PC (for AUIPC)
    input  wire [31:0] B,         // Operand B — comes from Register File (rs2) or Immediate value
    input  wire [3:0]  alu_ctrl,  // 4-bit code telling the ALU which operation to do
    output reg  [31:0] result,    // The computed result — goes to memory address or write-back
    output wire        zero,      // 1 if result == 0 (used by BEQ: branch if equal)
    output wire        negative,  // 1 if result is negative (MSB = 1 in 2's complement)
    output wire        overflow   // 1 if signed addition/subtraction overflowed
);

// ── ALU Control Encodings ────────────────────────────────────
// These 4-bit codes are generated by alu_control.v and tell
// this module which operation to perform.
// IMPORTANT: These values must exactly match what alu_control.v outputs!
localparam ALU_ADD  = 4'b0000;  // ADD / ADDI  → used for arithmetic and address calculation (LW/SW)
localparam ALU_SUB  = 4'b0001;  // SUB         → used for subtraction and branch comparisons (BEQ etc.)
localparam ALU_AND  = 4'b0010;  // AND / ANDI  → bitwise AND (masking bits)
localparam ALU_OR   = 4'b0011;  // OR  / ORI   → bitwise OR  (setting bits)
localparam ALU_XOR  = 4'b0100;  // XOR / XORI  → bitwise XOR (toggling bits)
localparam ALU_SLL  = 4'b0101;  // SLL / SLLI  → Shift Left Logical  (multiply by power of 2)
localparam ALU_SRL  = 4'b0110;  // SRL / SRLI  → Shift Right Logical  (divide by power of 2, unsigned)
localparam ALU_SRA  = 4'b0111;  // SRA / SRAI  → Shift Right Arithmetic (divide, signed — preserves sign bit)
localparam ALU_SLT  = 4'b1000;  // SLT / SLTI  → Set if A < B (signed comparison)  → result = 1 or 0
localparam ALU_SLTU = 4'b1001;  // SLTU/ SLTIU → Set if A < B (unsigned comparison) → result = 1 or 0
localparam ALU_LUI  = 4'b1010;  // LUI         → Pass B straight through (used to load upper 20 bits)

// ── ALU Operation ────────────────────────────────────────────
// always @(*) means this block re-runs whenever ANY input changes
// This makes it purely combinational (no clock needed — instant result)
always @(*) begin
    case (alu_ctrl)
        ALU_ADD  : result = A + B;

        ALU_SUB  : result = A - B;
                   // NOTE: SUB is also used for branch comparisons.
                   // For BEQ: if A-B == 0 (zero flag high), they are equal.

        ALU_AND  : result = A & B;   // Bitwise AND (both bits must be 1)

        ALU_OR   : result = A | B;   // Bitwise OR  (at least one bit must be 1)

        ALU_XOR  : result = A ^ B;   // Bitwise XOR (exactly one bit must be 1)

        ALU_SLL  : result = A << B[4:0];
                   // Shift Left Logical: A shifted left by B[4:0] positions
                   // We use only B[4:0] (5 bits) because max shift for 32-bit is 31
                   // Shifting left by N = multiplying by 2^N

        ALU_SRL  : result = A >> B[4:0];
                   // Shift Right Logical: fills vacated MSBs with 0s
                   // Used for unsigned right shift / division by 2^N

        ALU_SRA  : result = $signed(A) >>> B[4:0];
                   // Shift Right Arithmetic: fills MSBs with the SIGN BIT (bit 31)
                   // $signed() tells Verilog to treat A as a signed number
                   // >>> is the arithmetic shift operator in Verilog
                   // Used for signed division by power of 2

        ALU_SLT  : result = ($signed(A) < $signed(B)) ? 32'd1 : 32'd0;
                   // Set Less Than (signed): if A < B treat as signed, result = 1, else 0
                   // $signed() makes Verilog compare as 2's complement signed

        ALU_SLTU : result = (A < B) ? 32'd1 : 32'd0;
                   // Set Less Than Unsigned: treat A and B as unsigned raw bits

        ALU_LUI  : result = B;
                   // Load Upper Immediate: just pass B (the immediate) straight through
                   // The upper 20 bits of B are already set by imm_gen (U-type format)

        default  : result = 32'hDEAD_BEEF;
                   // Should NEVER be reached in correct operation.
                   // 0xDEADBEEF is a well-known debug sentinel — easy to spot in waveforms!
    endcase
end

// ── Status Flags ─────────────────────────────────────────────
// These are computed from the result and used by the PC logic
// to decide whether to take a branch.

// ZERO flag: result is exactly zero → used for BEQ (branch if equal)
// Example: BEQ rs1, rs2 → ALU does (rs1 - rs2) → if zero=1, they are equal
assign zero     = (result == 32'b0);

// NEGATIVE flag: the MSB (bit 31) of the result is 1
// In 2's complement: if bit 31 = 1, the number is negative
assign negative = result[31];

// OVERFLOW flag: detect signed arithmetic overflow
// Addition overflow:  both A and B are positive but result is negative (or both neg → positive)
// Subtraction overflow: similar but with B inverted (A - B = A + (-B))
//
// Formula for ADD overflow: (A≥0 AND B≥0 AND result<0) OR (A<0 AND B<0 AND result≥0)
// Verilog: ~A[31] means A is positive, A[31] means A is negative
assign overflow = (alu_ctrl == ALU_ADD) ?
                  (~A[31] & ~B[31] & result[31]) | (A[31] & B[31] & ~result[31]) :
                  (alu_ctrl == ALU_SUB) ?
                  (~A[31] & B[31] & result[31]) | (A[31] & ~B[31] & ~result[31]) :
                  1'b0;  // No overflow concept for logical operations

endmodule
